 export interface PrisonerSentenceDetails {
    bookingId: number
    offenderNo: string
    firstName: string
    lastName: string
    agencyLocationId: string
    mostRecentActiveBooking: boolean
    sentenceDetail: {
        tariffDate: any
        lateTermDate: any
        topupSupervisionExpiryDate: any
        earlyTermDate: any
        actualParoleDate: any
        tariffEarlyRemovalSchemeEligibilityDate: any
        earlyRemovalSchemeEligibilityDate: any
        releaseOnTemporaryLicenceDate: any
        homeDetentionCurfewEligibilityDate: any
        midTermDate: any
        homeDetentionCurfewActualDate: any
        dtoPostRecallReleaseDateOverride: any
        dtoPostRecallReleaseDate: any
        nonParoleOverrideDate: any
        nonParoleDate: any
        automaticReleaseDate: any
        postRecallReleaseDate: string
        automaticReleaseOverrideDate: any
        conditionalReleaseOverrideDate: string
        sentenceExpiryDate: string
        conditionalReleaseDate: string
        licenceExpiryDate: string
        paroleEligibilityDate: string
        effectiveSentenceEndDate: string
        bookingId: number
        sentenceStartDate: string
        postRecallReleaseOverrideDate: string
        nonDtoReleaseDate: string
        sentenceExpiryCalculatedDate: string
        licenceExpiryCalculatedDate: string
        paroleEligibilityOverrideDate: string
        nonDtoReleaseDateType: string
        confirmedReleaseDate: string
        releaseDate: string
    },
    dateOfBirth: string
    agencyLocationDesc: string
    internalLocationDesc: string
    facialImageId: number
}