export interface PrisonerSentenceDetails {
  bookingId: number
  offenderNo: string
  firstName: string
  lastName: string
  agencyLocationId: string
  mostRecentActiveBooking: boolean
  sentenceDetail: {
    tariffDate?: string
    lateTermDate?: string
    topupSupervisionExpiryDate?: string
    earlyTermDate?: string
    actualParoleDate?: string
    tariffEarlyRemovalSchemeEligibilityDate?: string
    earlyRemovalSchemeEligibilityDate?: string
    releaseOnTemporaryLicenceDate?: string
    homeDetentionCurfewEligibilityDate?: string
    midTermDate?: string
    homeDetentionCurfewActualDate?: string
    dtoPostRecallReleaseDateOverride?: string
    dtoPostRecallReleaseDate?: string
    nonParoleOverrideDate?: string
    nonParoleDate?: string
    automaticReleaseDate?: string
    postRecallReleaseDate?: string
    automaticReleaseOverrideDate?: string
    conditionalReleaseOverrideDate?: string
    sentenceExpiryDate?: string
    conditionalReleaseDate?: string
    licenceExpiryDate?: string
    paroleEligibilityDate?: string
    effectiveSentenceEndDate?: string
    bookingId?: number
    sentenceStartDate?: string
    postRecallReleaseOverrideDate?: string
    nonDtoReleaseDate?: string
    sentenceExpiryCalculatedDate?: string
    licenceExpiryCalculatedDate?: string
    paroleEligibilityOverrideDate?: string
    nonDtoReleaseDateType?: string
    confirmedReleaseDate?: string
    releaseDate?: string
  }
  dateOfBirth: string
  agencyLocationDesc: string
  internalLocationDesc: string
  facialImageId: number
}
