---
generic-service:
  nameOverride: hmpps-prisoner-profile
  serviceAccountName: hmpps-prisoner-profile
  productId: DPS040

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prisoner-profile
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-prisoner-profile-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-prisoner-profile"
    CONTENTFUL_HOST: "https://graphql.contentful.com"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-prisoner-profile:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SYSTEM_CLIENT_ID_CURIOUS: "SYSTEM_CLIENT_ID_CURIOUS"
      SYSTEM_CLIENT_SECRET_CURIOUS: "SYSTEM_CLIENT_SECRET_CURIOUS"
      SESSION_SECRET: "SESSION_SECRET"
      TAG_MANAGER_CONTAINER_ID: "TAG_MANAGER_CONTAINER_ID"
      CONTENTFUL_SPACE_ID: "CONTENTFUL_SPACE_ID"
      CONTENTFUL_ACCESS_TOKEN: "CONTENTFUL_ACCESS_TOKEN"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-profile
