---
# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-preprod.digital.prison.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://preprod.moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-preprod.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://preprod-api.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api-preprod.hmpps.service.justice.gov.uk"

    OFFENDER_CATEGORISATION_UI_URL: "https://preprod.offender-categorisation.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://preprod.use-of-force.service.justice.gov.uk"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder-preprod.hmpps.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://preprod.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome-preprod.prison.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk"
    FEEDBACK_DISABLED_PRISONS: "LEI,FNI,RSI"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: "PRE-PRODUCTION"

  allowlist:
    office: "217.33.148.210/32"
    quantum: "62.25.109.197/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    quantum_alt: "212.137.36.230/32"
    health-kick: "35.177.252.195/32"
    digitalprisons1: "52.56.112.98/32"
    digitalprisons2: "52.56.118.154/32"
    mojvpn: "81.134.202.29/32"
    j5-phones-1: "35.177.125.252/32"
    j5-phones-2: "35.177.137.160/32"
    sodexo-northumberland: "88.98.48.10/32"
    sodexo-northumberland2: "51.148.47.137/32"
    sodoxeo-forest-bank: "51.155.85.249/32"
    sodexo-peterborough: "51.155.55.241/32"
    serco: "217.22.14.0/24"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    oakwood-01: "217.161.76.184/29"
    oakwood-02: "217.161.76.192/29"
    oakwood-1: "217.161.76.187/32"
    oakwood-2: "217.161.76.195/32"
    oakwood-3: "217.161.76.186/32"
    oakwood-4: "217.161.76.194/32"
    durham-tees-valley: "51.179.197.1/32"
    interservfls: "51.179.196.131/32"
    sodexo1: "80.86.46.16/32"
    sodexo2: "80.86.46.17/32"
    sodexo3: "80.86.46.18/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    dxc_webproxy1: "195.92.38.20/32"
    dxc_webproxy2: "195.92.38.21/32"
    dxc_webproxy3: "195.92.38.22/32"
    dxc_webproxy4: "195.92.38.23/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"
    crc-rrp: "62.253.83.37/32"
    crc-pp-wwm: "5.153.255.210/32"
    moj-official-ark-c-expo-e: "51.149.249.0/29"
    moj-official-ark-c-vodafone: "194.33.248.0/29"
    moj-official-ark-f-vodafone: "194.33.249.0/29"
    moj-official-ark-f-expo-e: "51.149.249.32/29"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
