# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-dev.digital.prison.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_github_team: "connect-dps"
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleRemoveById 949110
      SecRuleRemoveById 942440
      SecRuleRemoveById 920300

  env:
    INGRESS_URL: "https://prisoner-dev.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-dev.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://dev.moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-dev.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://testservices.sequation.net/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api-dev.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://dev.offender-case-notes.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-dev.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://dev-api.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"

    OFFENDER_CATEGORISATION_UI_URL: "https://dev.offender-categorisation.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://dev.use-of-force.service.justice.gov.uk"
    USE_OF_FORCE_DISABLED_PRISONS: "CKI,FYI,WNI,WYI"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder-dev.hmpps.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://dev.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases-dev.hmpps.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome-dev.prison.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence-dev.hmpps.service.justice.gov.uk"
    MANAGE_ADJUDICATIONS_API_URL: "https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-dev.hmpps.service.justice.gov.uk"
    NON_ASSOCIATIONS_UI_URL: "https://non-associations-dev.hmpps.service.justice.gov.uk"
    FEEDBACK_DISABLED_PRISONS: "AGI,DNI,FNI,HDI,HLI,HMI,LEI,LHI,MDI,NHI,RSI,WDI,WEI,WYI"
    ENVIRONMENT_NAME: "DEV"
    NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-dev.hmpps.service.justice.gov.uk"
    ACTIVITIES_URL: "https://activities-dev.prison.service.justice.gov.uk/activities"
    ACTIVITIES_ENABLED_PRISONS: "LEI,RSI,LPI"
    APPOINTMENTS_URL: "https://activities-dev.prison.service.justice.gov.uk/appointments"
    APPOINTMENTS_ENABLED_PRISONS: "LEI,RSI,LPI"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    COMPONENT_API_LATEST: "true"
    PROFILE_ADD_APPOINTMENT_ENABLED: "true"
    PRISONER_PROFILE_DELIUS_API_URL: "https://prisoner-profile-and-delius-dev.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "true"
    ADJUDICATIONS_UI_URL: "https://manage-adjudications-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod
