generic-service:
  replicaCount: 4

  ingress:
    host: prisoner.digital.prison.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_github_team: "connect-dps"
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleRemoveById 949110
      SecRuleRemoveById 942440
      SecRuleRemoveById 920300

  autoscaling:
    enabled: true
    minReplicas: 8
    maxReplicas: 16
    targetCPUUtilizationPercentage: 1600

  env:
    INGRESS_URL: "https://prisoner.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://liveservices.sequation.com/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://offender-case-notes.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://api.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api.hmpps.service.justice.gov.uk"

    OFFENDER_CATEGORISATION_UI_URL: "https://offender-categorisation.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://use-of-force.service.justice.gov.uk"
    USE_OF_FORCE_DISABLED_PRISONS: "CKI,FYI,WNI,WYI"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder.hmpps.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases.hmpps.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome.prison.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence.hmpps.service.justice.gov.uk"
    MANAGE_ADJUDICATIONS_API_URL: "https://manage-adjudications-api.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates.hmpps.service.justice.gov.uk"
    NON_ASSOCIATIONS_UI_URL: "https://non-associations.hmpps.service.justice.gov.uk"
    FEEDBACK_DISABLED_PRISONS: "AGI,DNI,FNI,HDI,HLI,HMI,LEI,LHI,MDI,NHI,RSI,WDI,WEI,WYI"
    NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api.hmpps.service.justice.gov.uk"
    ACTIVITIES_URL: "https://activities.prison.service.justice.gov.uk/activities"
    ACTIVITIES_ENABLED_PRISONS: "RSI,LPI"
    APPOINTMENTS_URL: "https://activities.prison.service.justice.gov.uk/appointments"
    APPOINTMENTS_ENABLED_PRISONS: "RSI,LPI"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    COMPONENT_API_LATEST: "false"
    PROFILE_ADD_APPOINTMENT_ENABLED: "true"
    PRISONER_PROFILE_DELIUS_API_URL: "https://prisoner-profile-and-delius.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "true"

  allowlist:
    sscl-blackpool: 31.121.5.27/32
    sscl-azure: 51.142.106.199/32
    sscl-york: 62.6.61.29/32
    sscl-newcastle: 62.172.79.105/32
    sscl-newport: 217.38.237.212/32
    groups:
    - internal
    - prisons
    - private_prisons
    - police

generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-prod
