---
# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-dev.digital.prison.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://prisoner-dev.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-dev.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api-dev.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://dev.moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-dev.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://testservices.sequation.net/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api-dev.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://dev.offender-case-notes.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-dev.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://dev-api.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api-dev.hmpps.service.justice.gov.uk"

    OFFENDER_CATEGORISATION_UI_URL: "https://dev.offender-categorisation.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://dev.use-of-force.service.justice.gov.uk"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder-dev.hmpps.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://dev.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases-dev.hmpps.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome-dev.prison.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence-dev.hmpps.service.justice.gov.uk"
    MANAGE_ADJUDICATIONS_API_URL: "https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-dev.hmpps.service.justice.gov.uk"
    FEEDBACK_DISABLED_PRISONS: "LEI,FNI,RSI"
    SYSTEM_PHASE: "DEV"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
