# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-preprod.digital.prison.service.justice.gov.uk
    modsecurity_enabled: false
    modsecurity_github_team: "connect-dps"
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecAuditEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=connect-dps,tag:namespace=hmpps-prisoner-profile-preprod"
      SecAuditLog /var/log/nginx/error.log
      SecAuditLogType Serial
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

  env:
    ENVIRONMENT_NAME: "PRE-PRODUCTION"
    INGRESS_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    CONTENTFUL_ENVIRONMENT: "master"

    # UI Service urls
    ADJUDICATIONS_UI_URL: "https://manage-adjudications-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder-preprod.hmpps.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk"
    NON_ASSOCIATIONS_UI_URL: "https://non-associations-preprod.hmpps.service.justice.gov.uk"
    OFFENDER_CATEGORISATION_UI_URL: "https://preprod.offender-categorisation.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://preprod.pathfinder.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://preprod.use-of-force.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome-preprod.prison.service.justice.gov.uk"
    LEARNING_AND_WORK_PROGRESS_UI_URL: "https://learning-and-work-progress-preprod.hmpps.service.justice.gov.uk"
    CHANGE_SOMEONES_CELL_UI_URL: "https://change-someones-cell-preprod.prison.service.justice.gov.uk"
    INCENTIVES_UI_URL: "https://incentives-ui-preprod.hmpps.service.justice.gov.uk"
    CSIP_UI_URL: "https://csip-preprod.hmpps.service.justice.gov.uk"

    # API Service urls
    ACTIVITIES_URL: "https://activities-preprod.prison.service.justice.gov.uk/activities"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://preprod.moic.service.justice.gov.uk"
    APPOINTMENTS_URL: "https://activities-preprod.prison.service.justice.gov.uk/appointments"
    BOOK_A_VIDEO_LINK_API_URL: "https://book-a-video-link-api-preprod.prison.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
    COMPLEXITY_OF_NEED_API_URL: "https://complexity-of-need-preprod.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-preprod.hmpps.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-preprod.hmpps.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    MANAGE_ADJUDICATIONS_API_URL: "https://manage-adjudications-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://preprod-api.pathfinder.service.justice.gov.uk"
    PRISONER_PROFILE_DELIUS_API_URL: "https://prisoner-profile-and-delius-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    LOCATIONS_INSIDE_PRISON_API_URL: https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk
    NOMIS_SYNC_PRISONER_MAPPING_API_URL: https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API_URL: "https://learningandworkprogress-api-preprod.hmpps.service.justice.gov.uk"
    RESTRICTED_PATIENT_API_URL: "https://restricted-patients-api-preprod.hmpps.service.justice.gov.uk"
    CCRD_UI_URL: "https://court-cases-release-dates-preprod.hmpps.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    ALERTS_API_URL: "https://alerts-api-preprod.hmpps.service.justice.gov.uk"
    PRISON_PERSON_API_URL: "https://prison-person-api-preprod.prison.service.justice.gov.uk"
    PERSON_INTEGRATION_API_URL: "https://person-integration-api-preprod.hmpps.service.justice.gov.uk"
    CSIP_API_URL: "https://csip-api-preprod.hmpps.service.justice.gov.uk"
    HEALTH_AND_MEDICATION_API_URL: "https://health-and-medication-api-preprod.hmpps.service.justice.gov.uk"
    CONTENTFUL_HOST: "https://graphql.eu.contentful.com"

    # Feature flags
    AUDIT_ENABLED: "true"
    COMPONENT_API_LATEST: "true"
    FEEDBACK_DISABLED_PRISONS: "AGI,DNI,FNI,HDI,HLI,HMI,LEI,LHI,MDI,NHI,RSI,WDI,WEI,WYI"
    NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
    PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "AGI,BZI,DHI,DWI,ESI,EWI,FHI,LNI,NHI,PFI,SDI,STI"
    PROFILE_ADD_APPOINTMENT_ENABLED: "true"
    USE_OF_FORCE_DISABLED_PRISONS: "FYI,WNI,WYI"
    COURT_CASES_SUMMARY_ENABLED: "true"
    EDIT_PROFILE_ENABLED: "true"
    EDIT_PROFILE_ENABLED_PRISONS: "KMI"
    PRISON_PERSON_API_ENABLED: "false"
    PRISON_PERSON_API_ENABLED_PRISONS: ""
    DIET_AND_ALLERGY_ENABLED: "true"
    DIET_AND_ALLERGY_ENABLED_PRISONS: "STI"
    MILITARY_HISTORY_ENABLED: "true"

  allowlist:
    sscl-blackpool: 31.121.5.27/32
    sscl-azure: 51.142.106.199/32
    sscl-york: 62.6.61.29/32
    sscl-newcastle: 62.172.79.105/32
    sscl-newport: 217.38.237.212/32
    groups:
      - internal
      - prisons
      - private_prisons

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9.30pm UTC Monday-Friday

generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod
  businessHoursOnly: true

  elastiCacheAlertsClusterIds:
    cp-546b408b8600f28d-001: "HMPPS Prisoner Profile ElastiCache Cluster Node 1"
    cp-546b408b8600f28d-002: "HMPPS Prisoner Profile ElastiCache Cluster Node 2"
