# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-preprod.digital.prison.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_github_team: "connect-dps"

  env:
    INGRESS_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://preprod.moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    CASE_NOTES_API_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-preprod.hmpps.service.justice.gov.uk"
    PATHFINDER_API_URL: "https://preprod-api.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_API_URL: "https://manage-soc-cases-api-preprod.hmpps.service.justice.gov.uk"

    OFFENDER_CATEGORISATION_UI_URL: "https://preprod.offender-categorisation.service.justice.gov.uk"
    USE_OF_FORCE_UI_URL: "https://preprod.use-of-force.service.justice.gov.uk"
    USE_OF_FORCE_DISABLED_PRISONS: "CKI,FYI,WNI,WYI"
    MANAGE_A_WARRANT_FOLDER_UI_URL: "https://manage-a-warrant-folder-preprod.hmpps.service.justice.gov.uk"
    PATHFINDER_UI_URL: "https://preprod.pathfinder.service.justice.gov.uk"
    MANAGE_SOC_CASES_UI_URL: "https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk"
    WELCOME_PEOPLE_INTO_PRISON_UI_URL: "https://welcome-preprod.prison.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_UI_URL: "https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk"
    MANAGE_ADJUDICATIONS_API_URL: "https://manage-adjudications-api-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    NON_ASSOCIATIONS_UI_URL: "https://non-associations-preprod.hmpps.service.justice.gov.uk"
    FEEDBACK_DISABLED_PRISONS: "AGI,DNI,FNI,HDI,HLI,HMI,LEI,LHI,MDI,NHI,RSI,WDI,WEI,WYI"
    ENVIRONMENT_NAME: "PRE-PRODUCTION"
    NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-preprod.hmpps.service.justice.gov.uk"
    ACTIVITIES_URL: "https://activities-preprod.prison.service.justice.gov.uk/activities"
    ACTIVITIES_ENABLED_PRISONS: "RSI"
    APPOINTMENTS_URL: "https://activities-preprod.prison.service.justice.gov.uk/appointments"
    APPOINTMENTS_ENABLED_PRISONS: ""
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    COMPONENT_API_LATEST: "true"
    PROFILE_ADD_APPOINTMENT_ENABLED: "true"
    PRISONER_PROFILE_DELIUS_API_URL: "https://prisoner-profile-and-delius-preprod.hmpps.service.justice.gov.uk"

  allowlist:
    sscl-blackpool: 31.121.5.27/32
    sscl-azure: 51.142.106.199/32
    sscl-york: 62.6.61.29/32
    sscl-newcastle: 62.172.79.105/32
    sscl-newport: 217.38.237.212/32
    groups:
      - internal
      - prisons
      - private_prisons
      - police

generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod
