---
# Per environment values which override defaults in hmpps-prisoner-profile/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-preprod.digital.prison.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://preprod.moic.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
